// Code generated by foundation httpcontract; DO NOT EDIT.

package pasteerr

import (
	"sort"

	"github.com/yueli-official/foundation/go/problem"
)

const (
	CodeAnonymousCreationOff = "paste.anonymous_creation_disabled"
	CodeConflict             = "paste.conflict"
	CodeCreationSuspended    = "paste.creation_suspended"
	CodeDailyLimitReached    = "paste.daily_limit_reached"
	CodeForbidden            = "paste.forbidden"
	CodeGone                 = "paste.gone"
	CodeUnauthorized         = "paste.not_authenticated"
	CodeNotFound             = "paste.not_found"
	CodePasswordInvalid      = "paste.password_invalid"
	CodePasswordNeeded       = "paste.password_required"
)

var descriptors = map[string]problem.Descriptor{
	CodeAnonymousCreationOff: descriptor(CodeAnonymousCreationOff, 403),
	CodeConflict:             descriptor(CodeConflict, 409),
	CodeCreationSuspended:    descriptor(CodeCreationSuspended, 403),
	CodeDailyLimitReached:    descriptor(CodeDailyLimitReached, 429),
	CodeForbidden:            descriptor(CodeForbidden, 403),
	CodeGone:                 descriptor(CodeGone, 410),
	CodeUnauthorized:         descriptor(CodeUnauthorized, 401),
	CodeNotFound:             descriptor(CodeNotFound, 404),
	CodePasswordInvalid:      descriptor(CodePasswordInvalid, 403),
	CodePasswordNeeded:       descriptor(CodePasswordNeeded, 423),
}

func descriptor(code string, status int) problem.Descriptor {
	return problem.MustDescriptor(problem.MustKind(code, status), "https://errors.yueli.dev/problems/"+code)
}

func DescriptorForCode(code string) (problem.Descriptor, bool) {
	value, ok := descriptors[code]
	return value, ok
}

type CatalogEntry struct {
	Code   string `json:"code"`
	Status int    `json:"status"`
}

func Catalog() []CatalogEntry {
	result := make([]CatalogEntry, 0, len(descriptors))
	for code, value := range descriptors {
		result = append(result, CatalogEntry{Code: code, Status: value.Kind().Status()})
	}
	sort.Slice(result, func(i, j int) bool { return result[i].Code < result[j].Code })
	return result
}
